from .query_normalizer import normalize_query


TEST_GROUPS = {
        "GEN-Z / CASUAL / WHATSAPP STYLE": [
        "hey bro wassup",
        "hey bro whats up?",
        "yo wassup",
        "yo what do u guys do?",
        "hey guys what services u got?",
        "hey what all do u guys offer?",
        "sup guys",
        "sup",
        "heyy whats good?",
        "hey whats good",
        "yo guys",
        "hey fam what services do u provide?",
        "bro what services u guys got?",
        "bro do u guys do ppf?",
        "bro how much for ppf?",
        "bro ppf price?",
        "bro how much does ppf cost?",
        "bro can u do ppf on my bmw?",
        "bro u guys got ceramic coating?",
        "hey man do u guys do ceramic?",
        "hey dude what services u provide?",
        "yo do u guys have ppf?",
        "yo how much is ppf?",
        "yo can i get ppf done?",
        "hey guys i need ppf for my car",
        "hey bro i wanna get ppf done",
        "bro i need some car protection",
        "hey what can i get done for my car?",
        "what can u guys do for my ride?",
        "what services u got for my car?",
        "what all can u do to my car?",
        "u guys do car detailing?",
        "u guys do wrapping?",
        "u guys do ceramic coating?",
        "u guys do ppf or nah?",
        "ppf available or nah?",
        "ceramic coating available or nah?",
        "do u guys have ppf fr?",
        "is ppf worth it bro?",
        "how much is ppf tho?",
        "how much for ppf btw?",
        "ppf price pls",
        "ppf price bro?",
        "ppf cost tho?",
        "how long does ppf take tho?",
        "how long will it take bro?",
        "how long for ceramic coating?",
        "can u guys do it asap?",
        "can i get it done today?",
        "can i book this for tomorrow?",
        "any slots today?",
        "got any slots tomorrow?",
        "u guys open today?",
        "where u guys located?",
        "where are u guys at?",
        "send location pls",
        "drop ur location",
        "where's the studio?",
        "how does this work tho?",
        "what's the process bro?",
        "how does ppf work?",
        "what exactly is ceramic coating?",
        "is ppf safe tho?",
        "will ppf damage my paint?",
        "does ppf actually protect the car?",
        "what do i get with ppf?",
        "what's the deal with ppf?",
        "tell me about ppf bro",
        "i'm kinda interested in ppf",
        "thinking of getting ppf",
        "thinking about ceramic coating",
        "might get ppf for my car",
        "i wanna get my car protected",
        "need some protection for my ride",
        "my ride needs some protection lol",
        "i need ppf asap",
        "need ppf for my bmw asap",
        "can u guys hook me up with ppf?",
        "can u guys do this for me?",
        "i wanna get this done",
        "lemme know the price",
        "lmk the price",
        "lmk if u guys do ppf",
        "pls lmk the price",
        "lemme know if u have slots",
        "hit me up with the details",
        "send me the details pls",
        "gimme the details",
        "gimme the price",
        "just wanna know the price",
        "just checking how much ppf is",
        "just checking if u guys do ppf",
        "just wanted to know what u guys offer",
    ],
    "BASIC CHAT ABBREVIATIONS": [
        "what service u do?",
        "what services u provide?",
        "can u tell me about ppf?",
        "can u help me?",
        "pls tell me the price",
        "plz tell me about ceramic coating",
        "wht services u have?",
        "wht is ppf?",
        "wat services do u provide?",
        "r u open today?",
        "r ceramic coating available?",
    ],

    "WHATSAPP STYLE": [
        "hi what service u do",
        "hey u provide ppf?",
        "bro what services u have?",
        "pls tell me ppf price",
        "can u pls tell me the cost?",
        "i wanna know abt ppf",
        "i wanna know abt ceramic coating",
        "u guys do ceramic coating?",
        "u do car wrapping?",
        "u have ppf service?",
        "can u do it for my bmw?",
    ],

    "TYPOS": [
        "wht service u do?",
        "wht servise u provide?",
        "what servces u have?",
        "can u tell me the prce?",
        "how mch does ppf cost?",
        "hw much ppf cost?",
        "hw long ceramic coating take?",
        "ceramic coating availble?",
        "is ppf avalable?",
        "do u provde ppf?",
        "what is the proces?",
    ],

        "VERY MESSY CHAT INPUT": [
        "hey bro u guys ppf?",
        "hey bro ppf do u?",
        "u do ppf bro?",
        "ppf u guys have?",
        "ppf for bmw how much bro",
        "bmw ppf price pls",
        "ppf price for my car?",
        "car ppf how much?",
        "u guys do ceramic? how much?",
        "ceramic do u guys?",
        "what all u do cars?",
        "what u guys do for cars?",
        "u guys do what services?",
        "service u have for cars?",
        "what services got?",
        "what all service available?",
        "can do ppf my car?",
        "can u ppf my bmw?",
        "ppf my bmw possible?",
        "bmw 2 series ppf possible?",
        "ppf available for my car?",
        "can get ppf today?",
        "ppf today possible?",
        "tomorrow ppf slot?",
        "any slot for ppf tmrw?",
        "how much ppf roughly bro?",
        "ppf cost approx?",
        "ppf cost btw?",
        "ppf take how long?",
        "how long ppf bro?",
        "ppf how many days?",
        "ceramic how long take?",
        "what is ppf actually?",
        "ppf worth it?",
        "ppf safe?",
        "ppf damage paint?",
        "warranty on ppf?",
        "ppf warranty how much?",
        "what's included in ppf?",
        "ppf process what?",
    ],
        "EMOJI / PUNCTUATION / CASUAL": [
        "hey bro 👋",
        "yo guys 😎",
        "wassup!!",
        "hey!!! what do u guys do??",
        "ppf price??? 😭",
        "bro how much for ppf 😂",
        "ppf available??",
        "u guys do ceramic??",
        "how long does ppf take??",
        "can i book ppf today??",
        "ppf for bmw pls 🙏",
        "send location pls 📍",
        "any slots today? 🙏",
        "thanks bro 🙌",
        "thx guys ❤️",
    ],

    "MISSING WORDS / BROKEN ENGLISH": [
        "what service you do?",
        "what services you do?",
        "what service u have?",
        "which service available?",
        "ppf cost for bmw?",
        "ceramic coating price?",
        "ppf how much?",
        "how much ppf?",
        "ceramic coating how long?",
        "how long ppf take?",
        "ppf available my car?",
        "can ppf my bmw?",
        "you do ppf bmw?",
        "service for my car?",
    ],

    "SHORT QUERIES": [
        "ppf price",
        "ppf cost",
        "ceramic price",
        "ceramic cost",
        "ppf warranty",
        "ppf duration",
        "ceramic duration",
        "ppf process",
        "car wrapping",
        "studio location",
        "service list",
        "available services",
    ],

    "INFORMAL ENGLISH": [
        "how much will ppf be?",
        "how much for ppf?",
        "what will ppf cost me?",
        "how long will it take?",
        "how much time for ppf?",
        "do you guys do ppf?",
        "do u guys do ceramic coating?",
        "what all services do u have?",
        "what kind of services u guys provide?",
        "can i get ppf done?",
        "i need ppf for my car",
    ],

    "CONTRACTIONS / CHAT LANGUAGE": [
        "what's the price of ppf?",
        "whats the price of ppf?",
        "what's ppf cost?",
        "how's the process?",
        "i'd like to know about ppf",
        "i'm looking for ppf",
        "can't you do ppf?",
        "do you guys offer it?",
        "isn't ppf available?",
    ],

    "COMMON ABBREVIATIONS": [
        "pls give me info abt ppf",
        "plz send svc details",
        "need info abt ceramic",
        "ppf svc available?",
        "pls tell svc price",
        "need more info",
        "can u send info?",
        "thx for the info",
        "ty for helping",
    ],

    "LONGER NATURAL QUESTIONS": [
        "hey can u tell me what services u provide for cars?",
        "i want to know what all services you guys do",
        "can u tell me what kind of car services are available?",
        "i am looking for some protection for my car what services do u have?",
        "my car needs protection can u tell me which services u provide?",
        "can u tell me how much ppf will cost for my car?",
        "i wanna know how long ceramic coating will take",
        "can u tell me the process for getting ppf done?",
        "what options do u have for protecting my car?",
    ],

    "MIXED CASE / PUNCTUATION": [
        "WHAT SERVICE U DO?",
        "What Service u Provide?",
        "PPF PRICE???",
        "can u tell me the price!!!",
        "wht services u have.....",
        "HEY!!! WHAT DO U GUYS DO?",
        "ppf cost???",
        "ceramic coating price pls!!!",
    ],

    "CASUAL CUSTOMER LANGUAGE": [
        "hey bro what do u guys do?",
        "hi bro can u tell me the services?",
        "i need some car protection what can i get?",
        "my car needs ppf what should i do?",
        "i want to get ppf done",
        "can you guys do this for my car?",
        "what can i get done for my car?",
        "what do u suggest for car protection?",
    ],

    "MULTI-INTENT QUESTIONS": [
        "how much ppf cost and how long it take?",
        "what service u provide and what is the price?",
        "do u do ppf and how much?",
        "what services u have and how long they take?",
        "can u tell me ppf price and warranty?",
        "i wanna know ceramic coating price and process",
        "what options u have and how much they cost?",
    ],
}


for group_name, messages in TEST_GROUPS.items():

    print("\n")
    print("#" * 80)
    print(group_name)
    print("#" * 80)

    for number, message in enumerate(messages, start=1):

        normalized = normalize_query(message)

        print(f"\n{number}.")
        print(f"   ORIGINAL   : {message}")
        print(f"   NORMALIZED : {normalized}")